#!/bin/sh

#simple program to set background

#if [ ! -f "$1" ];then
#	exit
#fi

#this is for tile background
if [ "$1" = "-t" ];then
	if [ ! -f "$2" ];then
		exit
	fi
	feh --bg-tile "$2"
elif [ "$1" = "-s" ];then	
	if [ ! -f "$2" ];then
		exit
	fi
	feh  --bg-scale "$2"
else
	if [ ! -f "$1" ];then
		exit
	fi
 	feh --bg-fill "$1"
fi
